### ISSUE TITLE
dstar status

### ISSUE THREAD

**Issue by bitdivine** [dstarapp/ic-notes#1]
What is the current status of dstar?  I tried to create a new notebook but the creation is just hanging at the "Paying" stage.  I put 10 ICP in my dstar wallet, so funds are sufficient.  Are there some dstar canister that need to be topped up, maybe?

Btw, what is the best way of contacting you?  dscvr?  openchat?

**Comment by ic-dstar** [comment]
> What is the current status of dstar? I tried to create a new notebook but the creation is just hanging at the "Paying" stage. I put 10 ICP in my dstar wallet, so funds are sufficient. Are there some dstar canister that need to be topped up, maybe?
> 
> Btw, what is the best way of contacting you? dscvr? openchat?

Sorry, you can connect us on twitter @dstar_peter. thank you  for remind!
